/*
 Navicat Premium Data Transfer

 Source Server         : base
 Source Server Type    : MySQL
 Source Server Version : 80029
 Source Host           : 192.168.226.128:3306
 Source Schema         : backend-test

 Target Server Type    : MySQL
 Target Server Version : 80029
 File Encoding         : 65001

 Date: 11/06/2023 11:39:21
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for ROLE_PERMISSION
-- ----------------------------
DROP TABLE IF EXISTS `ROLE_PERMISSION`;
CREATE TABLE `ROLE_PERMISSION`  (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_ID` bigint NOT NULL COMMENT '角色ID',
  `PERMISSION_ID` bigint NOT NULL COMMENT '权限ID',
  `UNIQUE_ID` bigint NOT NULL DEFAULT 0,
  `DESCRIPTION` varchar(900) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '描述',
  `IS_DELETE` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `REVISION` int NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATED_ID` bigint NULL DEFAULT NULL COMMENT '创建人ID',
  `CREATED_BY` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_ID` bigint NULL DEFAULT NULL COMMENT '更新人ID',
  `UPDATED_BY` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `UNIQUE_ROLEID_PERMISSIONID`(`ROLE_ID` ASC, `PERMISSION_ID` ASC, `UNIQUE_ID` ASC) USING BTREE,
  INDEX `ROLEID_ISDELETE`(`ROLE_ID` ASC, `IS_DELETE` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 18 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '角色权限' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of ROLE_PERMISSION
-- ----------------------------
INSERT INTO `ROLE_PERMISSION` VALUES (1, 1, 1, 0, NULL, 0, 1, NULL, NULL, NULL, 1, 'Tommy', '2023-06-06 22:20:02');
INSERT INTO `ROLE_PERMISSION` VALUES (2, 1, 2, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (3, 1, 3, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (4, 1, 4, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (5, 1, 5, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (6, 1, 6, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (7, 1, 7, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (8, 1, 8, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (9, 1, 9, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (10, 1, 10, 0, NULL, 0, 1, 1, 'Tommy', '2023-06-06 22:27:15', 1, 'Tommy', '2023-06-06 22:33:45');
INSERT INTO `ROLE_PERMISSION` VALUES (11, 1, 11, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (12, 1, 12, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (13, 1, 13, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (14, 1, 14, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (15, 1, 15, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (16, 1, 16, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (17, 1, 17, 0, NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
